'use client'

import Link from 'next/link'
import { useQuery } from '@tanstack/react-query'
import { useAuth } from '@/hooks/useAuth'
import { getSupabase } from '@/lib/supabase'
import { fmt, fmtMonth, WHATSAPP_NUMBER } from '@/lib/constants'
import type { DbInvoice } from '@/types'
import Card       from '@/components/ui/Card'
import Button     from '@/components/ui/Button'
import StatusBadge from '@/components/ui/StatusBadge'
import { SkeletonCard } from '@/components/ui/Skeleton'
import UpiPaymentCard from '@/components/customer/UpiPaymentCard'
import toast from 'react-hot-toast'

export default function BillingView() {
  const { user } = useAuth()

  const { data: invoices = [], isPending } = useQuery({
    queryKey: ['customer', 'invoices-all', user?.id ?? null],
    enabled:  !!user,
    queryFn: async () => {
      const { data, error } = await getSupabase()
        .from('invoices')
        .select('*, payments(*)')
        .eq('user_id', user!.id)
        .order('created_at', { ascending: false })
      if (error) throw error
      return (data ?? []) as DbInvoice[]
    },
  })
  const loading = !!user && isPending

  const payViaWhatsApp = (inv: DbInvoice) => {
    const msg = encodeURIComponent(
      `Hello Dheera Fresh Milk! 💰\n\nI'd like to pay my invoice:\n\n` +
      `📄 Invoice: ${inv.invoice_number}\n` +
      `📅 Period:  ${fmtMonth(inv.month, inv.year)}\n` +
      `💵 Amount:  ₹${inv.pending_amount}\n\n` +
      `Please share UPI/payment details. Thank you!`
    )
    window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${msg}`, '_blank')
  }

  const downloadPDF = async (inv: DbInvoice) => {
    try {
      const { jsPDF }  = await import('jspdf')
      const autoTable  = (await import('jspdf-autotable')).default
      const doc        = new jsPDF()

      doc.setFontSize(22); doc.setTextColor(8, 37, 103)
      doc.text('Dheera Fresh Milk', 20, 22)
      doc.setFontSize(11); doc.setTextColor(75, 88, 120)
      doc.text('Farm Fresh Dairy – Whitefield, Bengaluru', 20, 30)
      doc.text('📞 +91 96205 44988  |  hello@dheerafreshmilk.com', 20, 37)

      doc.setFontSize(14); doc.setTextColor(8, 37, 103)
      doc.text(`Invoice: ${inv.invoice_number}`, 20, 52)
      doc.setFontSize(10); doc.setTextColor(75, 88, 120)
      doc.text(`Period:   ${fmtMonth(inv.month, inv.year)}`, 20, 59)
      doc.text(`Customer: ${user?.name ?? 'Customer'}  |  +91 ${user?.mobile}`, 20, 66)
      doc.text(`Due Date: ${inv.due_date ?? '—'}`, 20, 73)

      autoTable(doc, {
        startY: 82,
        head: [['Description', 'Deliveries', 'Litres', 'Amount']],
        body: [[
          'Cow Milk Subscription',
          String(inv.total_deliveries),
          `${inv.total_liters}L`,
          fmt(inv.total_amount),
        ]],
        foot: [
          ['', '', 'Total',   fmt(inv.total_amount)],
          ['', '', 'Paid',    fmt(inv.paid_amount)],
          ['', '', 'Pending', fmt(inv.pending_amount)],
        ],
        headStyles: { fillColor: [13, 59, 159] },
        footStyles: { fillColor: [30, 142, 62], textColor: [255, 255, 255] },
      })

      doc.save(`DFM-${inv.invoice_number}.pdf`)
      toast.success('Invoice downloaded!')
    } catch {
      toast.error('Failed to generate PDF')
    }
  }

  if (loading) return <div className="space-y-3"><SkeletonCard /><SkeletonCard /></div>

  const totalPending = invoices.reduce((s, i) => s + Number(i.pending_amount), 0)
  const hasPending   = totalPending > 0

  return (
    <div className="space-y-4 animate-fade-up">
      <h1 className="font-display font-bold text-2xl" style={{ color: 'var(--blue-deep)' }}>
        Billing &amp; Payments
      </h1>

      {hasPending && <UpiPaymentCard amount={totalPending} />}

      {invoices.length === 0 ? (
        <Card className="text-center py-12">
          <p className="text-4xl mb-3">📄</p>
          <p className="font-bold text-lg" style={{ color: 'var(--blue-deep)' }}>No invoices yet</p>
          <p className="text-sm mt-1" style={{ color: 'var(--text-muted)' }}>
            Invoices appear here once generated by the team
          </p>
        </Card>
      ) : (
        <div className="space-y-3">
          {invoices.map(inv => (
            <Card key={inv.id}>
              <div className="flex items-start justify-between mb-3">
                <div>
                  <p className="font-bold" style={{ color: 'var(--blue-deep)' }}>
                    {fmtMonth(inv.month, inv.year)}
                  </p>
                  <p className="text-xs mt-0.5 font-mono" style={{ color: 'var(--text-muted)' }}>
                    {inv.invoice_number}
                  </p>
                  <p className="text-xs" style={{ color: 'var(--text-muted)' }}>
                    {inv.total_deliveries} deliveries · {inv.total_liters}L
                  </p>
                </div>
                <StatusBadge status={inv.payment_status} />
              </div>

              {/* Amount breakdown */}
              <div className="grid grid-cols-3 gap-2 mb-3 p-3 rounded-xl" style={{ background: 'var(--blue-light)' }}>
                {[
                  { label: 'Total',   val: fmt(inv.total_amount),   color: 'var(--blue-deep)' },
                  { label: 'Paid',    val: fmt(inv.paid_amount),    color: 'var(--green)'     },
                  { label: 'Pending', val: fmt(inv.pending_amount), color: inv.pending_amount > 0 ? '#EF4444' : 'var(--green)' },
                ].map(a => (
                  <div key={a.label} className="text-center">
                    <p className="text-[10px] font-semibold mb-0.5" style={{ color: 'var(--text-muted)' }}>{a.label}</p>
                    <p className="font-bold text-sm" style={{ color: a.color }}>{a.val}</p>
                  </div>
                ))}
              </div>

              <div className="flex gap-2 flex-wrap">
                <Link href={`/dashboard/billing/${inv.id}`}>
                  <Button variant="outline" size="sm">📦 View details</Button>
                </Link>
                {inv.pending_amount > 0 && (
                  <Button variant="whatsapp" size="sm" onClick={() => payViaWhatsApp(inv)}>
                    💬 Pay via WhatsApp
                  </Button>
                )}
                {inv.payment_status === 'paid' ? (
                  <Button variant="ghost" size="sm" onClick={() => downloadPDF(inv)}>
                    ⬇ Download PDF
                  </Button>
                ) : (
                  <span
                    className="text-[11px] font-semibold px-3 py-1.5 rounded-lg"
                    title="Available once payment is recorded"
                    style={{ background: '#FFF3CD', color: '#856404' }}
                  >
                    Invoice Pending — pay to enable download
                  </span>
                )}
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  )
}
